name: build image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: tag and push devel image
        run: |
          docker build\
            --tag dmstraub/gramps-webapi:latest-devel \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
    #   - name: tag and push release image
    #     if: github.event_name == 'release'
    #     run: |
    #       docker build\
    #         --tag dmstraub/gramps-webapi:${{ github.event.release.tag_name }} \
    #         --tag dmstraub/gramps-webapi:latest \
    #         --platform linux/amd64,linux/arm/v7,linux/arm64 .
