name: build image

on:
  push:
    branches:
      - master
      - fix_heroku

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: gramps-webapi-demo
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true
        appdir: demo
