name: unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu dependencies
        run: sudo apt-get -y install gettext appstream pkg-config libcairo2-dev gir1.2-gtk-3.0 libgirepository1.0-dev libicu-dev libopencv-dev python3-opencv python3-numpy gramps
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install pycairo PyGObject pytest PyYAML jsonschema pyICU celery[pytest]
          pip install .
          pip list
      - name: Test with pytest
        run: pytest tests/test_endpoints/test_file.py -s
